const JOYSTICK_SIZE = 0.4;// In terms of the smaller of the two screen dimensions
const IS_TOUCH_DEVICE = true == ("ontouchstart" in window || window.DocumentTouch && document instanceof DocumentTouch);

const UPS = IS_TOUCH_DEVICE ? 15 : 60;// Reduced framerate on mobile
const NUM_RESOURCES = 197;
const IMAGE_DIR = "images/";
const SOUND_DIR = "sound/";
const SCREEN_WIDTH = 537;
const SCREEN_HEIGHT = 408;
const LEV_OFFSET_X = 16;
const LEV_OFFSET_Y = 79;
const LEV_DIMENSION_X = 21;
const LEV_DIMENSION_Y = 13;
const MENU_HEIGHT = 20;
const INTRO_DURATION = DEBUG ? 2 : 6;// In seconds
const LEV_START_DELAY = DEBUG ? 1 : 2;
const LEV_STOP_DELAY = DEBUG ? 1 : 2;
const ANIMATION_DURATION = Math.round(8*UPS/60);// How many times the game has to render before the image changes

const DEFAULT_VOLUME = 0.7;

const DIR_NONE = -1;
const DIR_UP = 0;
const DIR_LEFT = 1;
const DIR_DOWN = 2;
const DIR_RIGHT = 3;

const KEY_CODE_ENTER = 13;
const KEY_CODE_ESC   = 27;
const KEY_CODE_LEFT  = 37;
const KEY_CODE_UP    = 38;
const KEY_CODE_RIGHT = 39;
const KEY_CODE_DOWN  = 40;

const RENDER_FULL = 0;
const RENDER_TOP = 1;
const RENDER_BOTTOM = 2;
const RENDER_BOTTOM_BORDER = 3;

const DBX_CONFIRM = 0;
const DBX_SAVE = 1;
const DBX_LOAD = 2;
const DBX_CHPASS = 3;
const DBX_LOADLVL = 4;
const DBX_CHARTS = 5;

const ERR_SUCCESS = 0;
const ERR_EXISTS = 1;
const ERR_NOSAVE = 2;
const ERR_WRONGPW = 3;
const ERR_NOTFOUND = 4;
const ERR_EMPTYNAME = 5;



const IMG_BACKGROUND              = 0;
const IMG_TITLESCREEN             = 1;
const IMG_BANANA_PEEL             = 2;
const IMG_KEY_1                   = 3;
const IMG_KEY_2                   = 4;
const IMG_KEY_3                   = 5;
const IMG_KEY_4                   = 6;
const IMG_KEY_5                   = 7;
const IMG_KEY_6                   = 8;
const IMG_FOOTSTEPS               = 9;
const IMG_LADDER                  = 10;
const IMG_DIGIT_0                 = 11;
const IMG_DIGIT_1                 = 12;
const IMG_DIGIT_2                 = 13;
const IMG_DIGIT_3                 = 14;
const IMG_DIGIT_4                 = 15;
const IMG_DIGIT_5                 = 16;
const IMG_DIGIT_6                 = 17;
const IMG_DIGIT_7                 = 18;
const IMG_DIGIT_8                 = 19;
const IMG_DIGIT_9                 = 20;
const IMG_DIGIT_EMPTY             = 21;
const IMG_BTN_BERTI_UP            = 22;
const IMG_BTN_PREV_UP             = 23;
const IMG_BTN_NEXT_UP             = 24;
const IMG_BTN_BERTI_DOWN          = 25;
const IMG_BTN_PREV_DOWN           = 26;
const IMG_BTN_NEXT_DOWN           = 27;
const IMG_BTN_BERTI_BLINK_UP      = 28;
const IMG_BTN_PREV_DISABLED       = 29;
const IMG_BTN_NEXT_DISABLED       = 30;
const IMG_BLOCK_PINNED            = 31;
const IMG_BLOCK_LIGHT             = 32;
const IMG_BLOCK_HEAVY             = 33;
const IMG_BLOCK_DOOR_1            = 34; // Unused (duplicate)
const IMG_BLOCK_DOOR_2            = 35; // Unused (duplicate)
const IMG_BLOCK_DOOR_3            = 36; // Unused (duplicate)
const IMG_BLOCK_DOOR_4            = 37; // Unused (duplicate)
const IMG_BLOCK_DOOR_5            = 38; // Unused (duplicate)
const IMG_BLOCK_DOOR_6            = 39; // Unused (duplicate)
const IMG_NONE                    = 40; // Number 40 contains no image due to a miscalculation
const IMG_DOOR_1_CLOSED           = 41;
const IMG_DOOR_1_OPENING          = 42;
const IMG_DOOR_1_FADING           = 43;
const IMG_DOOR_2_CLOSED           = 44;
const IMG_DOOR_2_OPENING          = 45;
const IMG_DOOR_2_FADING           = 46;
const IMG_DOOR_3_CLOSED           = 47;
const IMG_DOOR_3_OPENING          = 48;
const IMG_DOOR_3_FADING           = 49;
const IMG_DOOR_4_CLOSED           = 50;
const IMG_DOOR_4_OPENING          = 51;
const IMG_DOOR_4_FADING           = 52;
const IMG_DOOR_5_CLOSED           = 53;
const IMG_DOOR_5_OPENING          = 54;
const IMG_DOOR_5_FADING           = 55;
const IMG_DOOR_6_CLOSED           = 56;
const IMG_DOOR_6_OPENING          = 57;
const IMG_DOOR_6_FADING           = 58;
const IMG_BERTI_IDLE              = 59;
const IMG_BERTI_BLINKING          = 60; // Unused, but should be used (Berti blinking when idle)
const IMG_BERTI_CELEBRATING       = 61;
const IMG_BERTI_DEAD              = 62;
const IMG_BERTI_WALK_LEFT_0       = 63;
const IMG_BERTI_WALK_LEFT_1       = 64;
const IMG_BERTI_WALK_LEFT_2       = 65;
const IMG_BERTI_WALK_LEFT_3       = 66;
const IMG_BERTI_WALK_RIGHT_0      = 67;
const IMG_BERTI_WALK_RIGHT_1      = 68;
const IMG_BERTI_WALK_RIGHT_2      = 69;
const IMG_BERTI_WALK_RIGHT_3      = 70;
const IMG_BERTI_WALK_UP_0         = 71;
const IMG_BERTI_WALK_UP_1         = 72;
const IMG_BERTI_WALK_UP_2         = 73;
const IMG_BERTI_WALK_UP_3         = 74;
const IMG_BERTI_WALK_DOWN_0       = 75;
const IMG_BERTI_WALK_DOWN_1       = 76;
const IMG_BERTI_WALK_DOWN_2       = 77;
const IMG_BERTI_WALK_DOWN_3       = 78;
const IMG_BERTI_PUSH_LEFT_0       = 79;
const IMG_BERTI_PUSH_LEFT_1       = 80;
const IMG_BERTI_PUSH_LEFT_2       = 81;
const IMG_BERTI_PUSH_LEFT_3       = 82;
const IMG_BERTI_PUSH_RIGHT_0      = 83;
const IMG_BERTI_PUSH_RIGHT_1      = 84;
const IMG_BERTI_PUSH_RIGHT_2      = 85;
const IMG_BERTI_PUSH_RIGHT_3      = 86;
const IMG_BERTI_PUSH_UP_0         = 87;
const IMG_BERTI_PUSH_UP_1         = 88;
const IMG_BERTI_PUSH_UP_2         = 89;
const IMG_BERTI_PUSH_UP_3         = 90;
const IMG_BERTI_PUSH_DOWN_0       = 91;
const IMG_BERTI_PUSH_DOWN_1       = 92;
const IMG_BERTI_PUSH_DOWN_2       = 93;
const IMG_BERTI_PUSH_DOWN_3       = 94;
const IMG_BERTI_WALK_LEFT_U_0     = 95;  // Unused (duplicate)
const IMG_BERTI_WALK_LEFT_U_1     = 96;  // Unused (duplicate)
const IMG_BERTI_WALK_LEFT_U_2     = 97;  // Unused (duplicate)
const IMG_BERTI_WALK_LEFT_U_3     = 98;  // Unused (duplicate)
const IMG_BERTI_WALK_RIGHT_U_0    = 99;  // Unused (duplicate)
const IMG_BERTI_WALK_RIGHT_U_1    = 100; // Unused (duplicate)
const IMG_BERTI_WALK_RIGHT_U_2    = 101; // Unused (duplicate)
const IMG_BERTI_WALK_RIGHT_U_3    = 102; // Unused (duplicate)
const IMG_BERTI_WALK_UP_U_0       = 103; // Unused (duplicate)
const IMG_BERTI_WALK_UP_U_1       = 104; // Unused (duplicate)
const IMG_BERTI_WALK_UP_U_2       = 105; // Unused (duplicate)
const IMG_BERTI_WALK_UP_U_3       = 106; // Unused (duplicate)
const IMG_BERTI_WALK_DOWN_U_0     = 107; // Unused (not a duplicate, minor differences)
const IMG_BERTI_WALK_DOWN_U_1     = 108; // Unused (not a duplicate, minor differences)
const IMG_BERTI_WALK_DOWN_U_2     = 109; // Unused (not a duplicate, minor differences)
const IMG_BERTI_WALK_DOWN_U_3     = 110; // Unused (not a duplicate, minor differences)
const IMG_PURPMON_STUCK_0         = 111;
const IMG_PURPMON_STUCK_1         = 112;
const IMG_PURPMON_STUCK_2         = 113;
const IMG_PURPMON_STUCK_3         = 114;
const IMG_PURPMON_WALK_LEFT_0     = 115;
const IMG_PURPMON_WALK_LEFT_1     = 116;
const IMG_PURPMON_WALK_LEFT_2     = 117;
const IMG_PURPMON_WALK_LEFT_3     = 118;
const IMG_PURPMON_WALK_RIGHT_0    = 119;
const IMG_PURPMON_WALK_RIGHT_1    = 120;
const IMG_PURPMON_WALK_RIGHT_2    = 121;
const IMG_PURPMON_WALK_RIGHT_3    = 122;
const IMG_PURPMON_WALK_UP_0       = 123;
const IMG_PURPMON_WALK_UP_1       = 124;
const IMG_PURPMON_WALK_UP_2       = 125;
const IMG_PURPMON_WALK_UP_3       = 126;
const IMG_PURPMON_WALK_DOWN_0     = 127;
const IMG_PURPMON_WALK_DOWN_1     = 128;
const IMG_PURPMON_WALK_DOWN_2     = 129;
const IMG_PURPMON_WALK_DOWN_3     = 130;
const IMG_PURPMON_PUSH_LEFT_0     = 131;
const IMG_PURPMON_PUSH_LEFT_1     = 132;
const IMG_PURPMON_PUSH_LEFT_2     = 133;
const IMG_PURPMON_PUSH_LEFT_3     = 134;
const IMG_PURPMON_PUSH_RIGHT_0    = 135;
const IMG_PURPMON_PUSH_RIGHT_1    = 136;
const IMG_PURPMON_PUSH_RIGHT_2    = 137;
const IMG_PURPMON_PUSH_RIGHT_3    = 138;
const IMG_PURPMON_PUSH_UP_0       = 139;
const IMG_PURPMON_PUSH_UP_1       = 140;
const IMG_PURPMON_PUSH_UP_2       = 141;
const IMG_PURPMON_PUSH_UP_3       = 142;
const IMG_PURPMON_PUSH_DOWN_0     = 143;
const IMG_PURPMON_PUSH_DOWN_1     = 144;
const IMG_PURPMON_PUSH_DOWN_2     = 145;
const IMG_PURPMON_PUSH_DOWN_3     = 146;
const IMG_GREENMON_STUCK_0        = 147;
const IMG_GREENMON_STUCK_1        = 148;
const IMG_GREENMON_STUCK_2        = 149;
const IMG_GREENMON_STUCK_3        = 150;
const IMG_GREENMON_WALK_LEFT_0    = 151;
const IMG_GREENMON_WALK_LEFT_1    = 152;
const IMG_GREENMON_WALK_LEFT_2    = 153;
const IMG_GREENMON_WALK_LEFT_3    = 154;
const IMG_GREENMON_WALK_RIGHT_0   = 155;
const IMG_GREENMON_WALK_RIGHT_1   = 156;
const IMG_GREENMON_WALK_RIGHT_2   = 157;
const IMG_GREENMON_WALK_RIGHT_3   = 158;
const IMG_GREENMON_WALK_UP_0      = 159;
const IMG_GREENMON_WALK_UP_1      = 160;
const IMG_GREENMON_WALK_UP_2      = 161;
const IMG_GREENMON_WALK_UP_3      = 162;
const IMG_GREENMON_WALK_DOWN_0    = 163;
const IMG_GREENMON_WALK_DOWN_1    = 164;
const IMG_GREENMON_WALK_DOWN_2    = 165;
const IMG_GREENMON_WALK_DOWN_3    = 166;
const IMG_ARGL                    = 167;
const IMG_WOW                     = 168;
const IMG_YEAH                    = 169;
const IMG_ENDSCREEN               = 170;
const IMG_CHECKBOX_CHECKED        = 171;
const IMG_CHECKBOX_UNCHECKED      = 172;
const IMG_DIALOGBOX_CONFIRM       = 173;
const IMG_DIALOGBOX_SAVELOAD      = 174;
const IMG_DIALOGBOX_LOADLVL       = 175;
const IMG_DIALOGBOX_CHARTS        = 176;
const IMG_BTN_CANCEL_UP           = 177;
const IMG_BTN_CANCEL_DOWN         = 178;
const IMG_BTN_NO_UP               = 179;
const IMG_BTN_NO_DOWN             = 180;
const IMG_BTN_OK_UP               = 181;
const IMG_BTN_OK_DOWN             = 182;
const IMG_BTN_YES_UP              = 183;
const IMG_BTN_YES_DOWN            = 184;

const IMG_DIGIT_LOOKUP = [
	IMG_DIGIT_0,
	IMG_DIGIT_1,
	IMG_DIGIT_2,
	IMG_DIGIT_3,
	IMG_DIGIT_4,
	IMG_DIGIT_5,
	IMG_DIGIT_6,
	IMG_DIGIT_7,
	IMG_DIGIT_8,
	IMG_DIGIT_9
];


const ENT_DUMMY          = -1; // Dummy block (invisible), prevents entities from moving to already occupied squares
const ENT_EMPTY          =  0; // Empty and unoccupied space
const ENT_PLAYER_BERTI   =  1; // Berti the garbage man, the entity that is controlled by the player
const ENT_AUTO_BERTI     =  2; // Berti clones that move automatically, as seen in the intro screen
const ENT_PINNED_BLOCK   =  3; // Solid, pinned block that cannot be moved
const ENT_BANANA_PEEL    =  4; // The banana peels which Berti needs to pick up to complete the levels
const ENT_LIGHT_BLOCK    =  5; // Light blue block with four arrows on it, pushable
const ENT_HEAVY_BLOCK    =  6; // Dark blue block with diamond shape <> on it, pushable if nothing is behind it
const ENT_PURPLE_MONSTER =  7; // Purple monster, can push blocks
const ENT_UNUSED_1       =  8; // Unused
const ENT_UNUSED_2       =  9; // Unused
const ENT_GREEN_MONSTER  = 10; // Green monster, cannot push blocks
const ENT_UNUSED_3       = 11; // Unused
const ENT_UNUSED_4       = 12; // Unused
const ENT_KEY_1          = 13; // Key which opens corresponding door
const ENT_KEY_2          = 14; // Key which opens corresponding door
const ENT_KEY_3          = 15; // Key which opens corresponding door
const ENT_KEY_4          = 16; // Key which opens corresponding door
const ENT_KEY_5          = 17; // Key which opens corresponding door
const ENT_KEY_6          = 18; // Key which opens corresponding door
const ENT_DOOR_1         = 19; // Door which is opened by corresponding key
const ENT_DOOR_2         = 20; // Door which is opened by corresponding key
const ENT_DOOR_3         = 21; // Door which is opened by corresponding key
const ENT_DOOR_4         = 22; // Door which is opened by corresponding key
const ENT_DOOR_5         = 23; // Door which is opened by corresponding key
const ENT_DOOR_6         = 24; // Door which is opened by corresponding key